---
title: Jekyll Starter
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: cydoval@mac.com
description: 'This is a Jekyll Starter template developed by cydoval.com.

'
baseurl: ''
url: http://yourdomain.com
twitter_username: cydoval
github_username: cydoval
markdown: kramdown
